license_choices:
  repository_license_choices:
  - given: "GPL-1.0-or-later OR Artistic-1.0"
    choice: "GPL-1.0-or-later"
  - given: "Artistic-1.0-Perl OR GPL-1.0-or-later"
    choice: "Artistic-1.0-Perl"
excludes:
  paths:
  - pattern: "3rdparty/openssl/tlsfuzzer/**"
    reason: "TEST_OF"
    comment: "Test suite for SSL & TLS, not included in production release."
  - pattern: "3rdparty/paho.mqtt.c/test/**"
    reason: "TEST_OF"
    comment: "Tests of the Paho C library, not included in production release."
  - pattern: "3rdparty/paho.mqtt.c/docs/**"
    reason: "DOCUMENTATION_OF"
    comment: "Code examples using Paho C library, not included in production release."
  - pattern: "3rdparty/paho.mqtt.c/test_package/**"
    reason: "TEST_OF"
    comment: "Tests of the Paho C library, not included in production release."
  - pattern: "3rdparty/paho.mqtt.cpp/test/**"
    reason: "TEST_OF"
    comment: "Tests of the Paho CPP library, not included in production release."
  - pattern: "3rdparty/openssl/pyca-cryptography/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Python cryptography tools, not included in production release."
  - pattern: "3rdparty/openssl/python-ecdsa/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Python cryptography tools, not included in production release."
  - pattern: "3rdparty/googletest/**"
    reason: "TEST_OF"
    comment: "Google test framework, not included in production release."
  - pattern: "3rdparty/openssl/wycheproof/**"
    reason: "TEST_OF"
    comment: "Crypto library testing, not included in production release."
  - pattern: "3rdparty/openssl/tlslite-ng/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Python library for SSL & TLS, not included in production release."
  - pattern: "3rdparty/openssl/krb5/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Kerberos not included in production release."
  - pattern: "3rdparty/curl/docs/**"
    reason: "DOCUMENTATION_OF"
    comment: "Code examples, not included in production release."
  - pattern: "3rdparty/curl/tests/**"
    reason: "TEST_OF"
    comment: "curl tests, not included in production release."
  - pattern: "3rdparty/glib/gio/tests/**"
    reason: "TEST_OF"
    comment: "Tests of glib, not included in production release."
  - pattern: "3rdparty/glib/gobject/tests/**"
    reason: "TEST_OF"
    comment: "Tests of glib, not included in production release."
  - pattern: "3rdparty/glib/glib/tests/**"
    reason: "TEST_OF"
    comment: "Tests of glib, not included in production release."
  - pattern: "3rdparty/openssl/external/perl/Text-Template-1.56/**"
    reason: "DOCUMENTATION_OF"
    comment: "Used in the generation of letters,HTML pages, not in production release."
  - pattern: "3rdparty/glib/po/**"
    reason: "OTHER"
    comment: "Languauge translator tool, not in production release."
  - pattern: "3rdparty/openssl/CHANGES.md"
    reason: "DOCUMENTATION_OF"
    comment: "Documents changes, not in production release."
  - pattern: "3rdparty/curl/LICENSES/**"
    reason: "DOCUMENTATION_OF"
    comment: "Copies of various licenses, not in production release."
  - pattern: "3rdparty/nlohmann-json/docs/**"
    reason: "DOCUMENTATION_OF"
    comment: "Used in the generation of documentation, not in production release."
  - pattern: "3rdparty/nlohmann-json/.reuse/**"
    reason: "DOCUMENTATION_OF"
    comment: "Documents dependencies for tests, not in production release."
  - pattern: "3rdparty/nlohmann-json/LICENSES/**"
    reason: "DOCUMENTATION_OF"
    comment: "Details of licenses used, not in production release."
  - pattern: "3rdparty/nlohmann-json/tests/thirdparty/imapdl/**"
    reason: "TEST_OF"
    comment: "Tests of nlohmann-json, not included in production release"
curations:
  license_findings:
  - path: "3rdparty/paho.mqtt.c/notice.html"
    detected_license: "LicenseRef-scancode-eclipse-sua-2011"
    concluded_license: "EPL-2.0"
    reason: "NOT_DETECTED"
    comment: "Correct format of the EPL license details not provided in notice.html file"
  - path: "3rdparty/paho.mqtt.cpp/notice.html"
    detected_license: "LicenseRef-scancode-eclipse-sua-2011"
    concluded_license: "EPL-1.0"
    reason: "NOT_DETECTED"
    comment: "Correct format of the EPL license details not provided in notice.html file"
  - path: "3rdparty/openssl/crypto/bio/bio_print.c"
    detected_license: "LicenseRef-scancode-snprintf"
    concluded_license: "Apache-2.0"
    reason: "DOCUMENTATION_OF"
    comment: "Documents that this particular code section is based on code written by Patrick Powell <papowell@astart.com>."
  - path: "3rdparty/glib/glib/gbsearcharray.h"
    detected_license: "LicenseRef-scancode-tim-janik-2003"
    concluded_license: "LGPL-2.1-or-later"
    reason: "DOCUMENTATION_OF"
    comment: "Documents that this code section is Copyright (C) 2000-2003 Tim Janik, redistribution and modification is permitted with provided disclaimer."
  - path: "3rdparty/glib/gio/gdbusconnection.c"
    detected_license: "GPL-2.0-only"
    concluded_license: "LGPL-2.1-or-later"
    reason: "DOCUMENTATION_OF"
    comment: "Documents licenses used in other library sources."
  - path: "3rdparty/glib/m4macros/glib-gettext.m4"
    detected_license: "GPL-1.0-or-later WITH LicenseRef-scancode-autoconf-simple-exception-2.0"
    concluded_license: "LGPL-2.1-or-later"
    reason: "DOCUMENTATION_OF"
    comment: "Documents an exception to GNU General Public License."
  - path: "3rdparty/glib/m4macros/glib-gettext.m4"
    detected_license: "GPL-1.0-or-later"
    concluded_license: "LGPL-2.1-or-later"
    reason: "CODE"
    comment: "License mentioned in code."
  - path: "3rdparty/glib/glib/gchecksum.c"
    detected_license: "LicenseRef-scancode-pycrypto"
    concluded_license: "LGPL-2.1-or-later"
    reason: "DOCUMENTATION_OF"
    comment: "Documents the origin of this code section (Copyright (C) 1995, A.M. Kuchling)."
  - path: "3rdparty/spdlog/include/spdlog/fmt/bundled/fmt.license.rst"
    detected_license: "Apache-2.0 WITH NOASSERTION"
    concluded_license: "MIT"
    reason: "DOCUMENTATION_OF"
    comment: "Additional details provided on this source code being embedded in another machine-executable object form of source code."
  - path: "3rdparty/spdlog/include/spdlog/fmt/bundled/format.h"
    detected_license: "Apache-2.0 WITH NOASSERTION"
    concluded_license: "MIT"
    reason: "DOCUMENTATION_OF"
    comment: "Additional details provided on this source code being embedded in another machine-executable object form of source code."
  - path: "3rdparty/curl/LICENSES/GPL-3.0-or-later.txt"
    detected_license: "GPL-3.0-only"
    concluded_license: "curl"
    reason: "DOCUMENTATION_OF"
    comment: "Copy of GNU GENERAL PUBLIC LICENSE."
  - path: "3rdparty/curl/scripts/copyright.pl"
    detected_license: "GPL-3.0-or-later"
    concluded_license: "curl"
    reason: "CODE"
    comment: "License name used in script."
  - path: "3rdparty/curl/scripts/copyright.pl"
    detected_license: "GPL-1.0-or-later"
    concluded_license: "curl"
    reason: "CODE"
    comment: "License name used in script."
  - path: "3rdparty/curl/m4/ax_compile_check_sizeof.m4"
    detected_license: "GPL-3.0-or-later"
    concluded_license: "curl"
    reason: "DOCUMENTATION_OF"
    comment: "Documents code tool provided under the GPL-3.0-or-later license (Copyright (c) 2008 Kaveh Ghazi <ghazi@caip.rutgers.edu>, Copyright (c) 2017 Reini Urban <rurban@cpan.org>)"
  - path: "3rdparty/glib/gobject/glib-genmarshal.in"
    detected_license: "GPL-1.0-or-later"
    concluded_license: "LGPL-2.1-or-later"
    reason: "CODE"
    comment: "GNU General Public License mentioned in string."
  - path: "3rdparty/openssl/crypto/aes/asm/bsaes-armv7.pl"
    detected_license: " GPL-1.0-or-later"
    concluded_license: "Apache-2.0"
    reason: "DOCUMENTATION_OF"
    comment: "Documents that specific modes/adaptations by Ard Biesheuvel of Linaro are licensed under GPL, the module is dual-licensed under OpenSSL and CRYPTOGAMS license."
  - path: "3rdparty/glib/glib-gettextize.in"
    detected_license: "GPL-2.0-or-later"
    concluded_license: "LGPL-2.1-or-later"
    reason: "DOCUMENTATION_OF"
    comment: "Documents permission to use under GPL, code used to 'internationalize' packages using gettext."
  - path: "3rdparty/glib/glib/gen-unicode-tables.pl"
    detected_license: "GPL-2.0-or-later"
    concluded_license: "LGPL-2.1-or-later"
    reason: "DOCUMENTATION_OF"
    comment: "Documents permission to use this perl script under GPL."
  - path: "3rdparty/glib/glib/gtree.c"
    detected_license: "LicenseRef-scancode-proprietary-license"
    concluded_license: "LGPL-2.1-or-later"
    reason: "INCORRECT"
    comment: "Invalid detection of a license issue."
  - path: "3rdparty/glib/gobject/glib-mkenums.in"
    detected_license: "GPL-2.0-only OR GPL-3.0-only"
    concluded_license: "LGPL-2.1-or-later"
    reason: "CODE"
    comment: "GNU General Public License mentioned in string."
  - path: "3rdparty/glib/gobject/glib-mkenums.in"
    detected_license: "GPL-3.0-only"
    concluded_license: "LGPL-2.1-or-later"
    reason: "CODE"
    comment: "GNU General Public License mentioned in string."
  - path: "3rdparty/openssl/crypto/camellia/asm/cmll-x86.pl"
    detected_license: "GPL-2.0-or-later OR LGPL-2.1-or-later OR MPL-1.1 OR BSD-3-Clause"
    concluded_license: "Apache-2.0"
    reason: "DOCUMENTATION_OF"
    comment: "Documents permission to use this perl script under GPL & LGPL."
  - path: "3rdparty/openssl/crypto/camellia/asm/cmll-x86_64.pl"
    detected_license: "GPL-2.0-or-later OR LGPL-2.1-or-later OR MPL-1.1 OR BSD-3-Clause"
    concluded_license: "Apache-2.0"
    reason: "DOCUMENTATION_OF"
    comment: "Documents permission to use this perl script under GPL & LGPL."
  - path: "3rdparty/openssl/crypto/sha/asm/sha256-armv4.pl"
    detected_license: "OpenSSL OR BSD-3-Clause OR GPL-1.0-or-later"
    concluded_license: "Apache-2.0"
    reason: "DOCUMENTATION_OF"
    comment: "Documents that this module is dual-licensed under OpenSSL and CRYPTOGAMS licenses."
  - path: "3rdparty/openssl/crypto/sha/asm/sha512-armv4.pl"
    detected_license: "OpenSSL OR BSD-3-Clause OR GPL-1.0-or-later"
    concluded_license: "Apache-2.0"
    reason: "DOCUMENTATION_OF"
    comment: "Documents that this module is dual-licensed under OpenSSL and CRYPTOGAMS licenses."
  - path: "3rdparty/openssl/crypto/sha/asm/sha512-armv8.pl"
    detected_license: "OpenSSL OR BSD-3-Clause OR GPL-1.0-or-later OR GPL-2.0-only"
    concluded_license: "Apache-2.0"
    reason: "DOCUMENTATION_OF"
    comment: "Documents that this module is dual-licensed under OpenSSL and CRYPTOGAMS licenses."
  packages:
  - id: "SpdxDocumentFile:IBM Corp.:paho.mqtt.c"
    curations:
      comment: "The license is not correctly detected, the concluded license for paho.mqtt.c is EPL-2.0."
      concluded_license: "EPL-2.0"
  - id: "SpdxDocumentFile::paho.mqtt.cpp"
    curations:
      comment: "The license is not correctly detected, the concluded license for paho.mqtt.cpp is EPL-1.0."
      concluded_license: "EPL-1.0"
